# Policy iteration

Policy Iteration (PI), Howard (1960), iterates between the policy evaluation phase, that computes the value function of the current policy, and the policy improvement phase, that computes an improved policy by a maximization over the value function. This is repeated until converging to an optimal policy.

Consider grid below:

![Example 4.1](images/example_4_1_sutton_barto.png)

The nonterminal states are $S = {1, 2, . . . , 14}$. There are four actions possible in each state, $A = \left\{ \textrm{up, down, right, left} \right\}$, which deterministically cause the corresponding state transitions, except that actions that would take the agent off the grid in fact leave the state unchanged. 

The reward is $−1$ on all transitions until the terminal state is reached. The terminal state is shaded in the figure (although it is shown in two places, it is formally one state). The expected reward function is thus $r(s, a, s') = −1$ for all states $s, s'$ and actions $a$.

## Getting environment set up

Setting up the grid, number of states, rewards for every state...

In [32]:
# Importing
import numpy as np
import gym

# Importing grid example as openAI gym
import gym_gridworlds

# Getting the environment that represent the example grid
env = gym.make('Gridworld-v0')

# States s = {s1 ... s14}
S = env.observation_space

# Actions A = {a1 ... 4}
A = env.action_space

# Transition function T or P that measures the prob
# of given an action a_i taken, ending up in state s_j
P = env.P

# Reward function
R = env.R

# Starting random policy (or PDF for action to take being in a state)
# Get random numbers and normalize to PDF in action axis 
pi = np.random.rand(S.n, A.n)
pi = pi / np.sum(pi, axis=1, keepdims=True)

# Random policy
print("Pi initial policy:")
print(pi)


Pi initial policy:
[[0.21377114 0.32625665 0.28662183 0.17335038]
 [0.01838916 0.19805375 0.39424971 0.38930738]
 [0.27214618 0.14436676 0.43832854 0.14515852]
 [0.34497464 0.01837791 0.30167073 0.33497671]
 [0.21928808 0.00252043 0.30156304 0.47662844]
 [0.30203349 0.31495458 0.33786305 0.04514888]
 [0.2382511  0.35971708 0.27779511 0.1242367 ]
 [0.22860847 0.08490726 0.07823468 0.60824959]
 [0.34258895 0.60995404 0.00368653 0.04377047]
 [0.31533965 0.38397744 0.23513801 0.0655449 ]
 [0.37033125 0.00426326 0.42087954 0.20452596]
 [0.44315223 0.07165464 0.36574997 0.11944317]
 [0.35213516 0.27373723 0.04187704 0.33225058]
 [0.33903907 0.0589333  0.2193766  0.38265103]
 [0.08922545 0.60882965 0.24286798 0.05907691]]


In [33]:
s_k0 = 1   # State 1
a = 2      # down
P_s_k1 = P[a][s_k0][:]

# This should transition to state 5 with prob = 1
P_s_k1


array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

## Policy Evaluation

TODO: Explain policy evaluation here

In [35]:
def policy_evaluation(pi, S, A, P):
    # Policy evaluation for being in each state
    # V = {v(s1), ... , v(s14)}
    V = np.zeros(S.n)
    
    # Convergence condition
    theta = 0.001
    
    # Repeat till convergence
    while True:
        for s in range(S.n):
            v = V[s]
            # TODO!
            break

## Policy Improvement

TODO: Explain policy improvement here